# 此文件将用于开发环境
version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 8080:8080
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules